In [2]:
import numpy as np
import pandas as pd
import scipy as sc

normal_distrib = np.random.normal(0, 10, 10000)
normal_distrib = pd.DataFrame(normal_distrib)
normal_distrib.describe(percentiles=[0.25, 0.5, 0.75, 0.021, 0.136, 0.5 + 0.341, 0.5 + 0.341 + 0.136])

n = 4
sum =10
a = 1/3*1**n*np.exp(-1*sum)
b = 1/2*0.5**n*np.exp(-0.5*sum)
c = 1/6*0.25**n*np.exp(-0.25*sum)

(a+0.5*b+0.25*c)/(a+b+c), a, b, c

(0.4792446825796688,
 1.5133309920828285e-05,
 0.00021056084372142084,
 5.344075431243411e-05)

In [6]:
P=0.3
n=12
k=5

probs = [sc.special.comb(n, k)*P**k*(1-P)**(n-k) for k in range(0, n+1)]
prefix_sum = np.cumsum(probs[::-1])
prefix_sum, probs, prefix_sum < 0.05, prefix_sum[::-1][5]

(array([5.31441000e-07, 1.54117890e-05, 2.06376255e-04, 1.69165543e-03,
        9.48937113e-03, 3.86008431e-02, 1.17848739e-01, 2.76344530e-01,
        5.07484227e-01, 7.47184652e-01, 9.14974950e-01, 9.86158713e-01,
        1.00000000e+00]),
 [0.01384128720099999,
  0.07118376274799995,
  0.1677902979059999,
  0.23970042557999985,
  0.2311396960949999,
  0.1584957916079999,
  0.07924789580399996,
  0.029111471927999982,
  0.007797715694999996,
  0.0014852791799999992,
  0.00019096446599999988,
  1.4880347999999992e-05,
  5.314409999999998e-07],
 array([ True,  True,  True,  True,  True,  True, False, False, False,
        False, False, False, False]),
 0.27634453046999985)

In [5]:
P=0.7
n=12
k=5

probs = [sc.special.comb(n, k)*P**k*(1-P)**(n-k) for k in range(0, n+1)]
prefix_sum = np.cumsum(probs)
prefix_sum, probs, prefix_sum[0:7]

(array([5.31441000e-07, 1.54117890e-05, 2.06376255e-04, 1.69165544e-03,
        9.48937113e-03, 3.86008431e-02, 1.17848739e-01, 2.76344530e-01,
        5.07484227e-01, 7.47184652e-01, 9.14974950e-01, 9.86158713e-01,
        1.00000000e+00]),
 [5.314410000000009e-07,
  1.4880348000000022e-05,
  0.00019096446600000026,
  0.0014852791800000014,
  0.007797715695000007,
  0.02911147192800002,
  0.07924789580400005,
  0.15849579160800004,
  0.231139696095,
  0.23970042558,
  0.16779029790599995,
  0.07118376274799997,
  0.01384128720099999],
 array([5.31441000e-07, 1.54117890e-05, 2.06376255e-04, 1.69165544e-03,
        9.48937113e-03, 3.86008431e-02, 1.17848739e-01]))